# -*- coding: utf-8 -*-
"""Final Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIO-78QEb_dBeOiKvpoYKtUYvmgHgr0L
"""

from google.colab import drive
drive.mount('/content/drive')

import joblib
import re

# Load vectorizers
vectorizer_xgb = joblib.load('/content/drive/MyDrive/tfidf_vectorizer.pkl')
vectorizer_lgbm = joblib.load('/content/drive/MyDrive/lgb_vectorizer.pkl')
vectorizer_logreg = joblib.load('/content/drive/MyDrive/logreg_vectorizer.pkl')

# Load models
xgb_model = joblib.load('/content/drive/MyDrive/xgb_model.pkl')
lgbm_model = joblib.load('/content/drive/MyDrive/lgb_model.pkl')
logreg_model = joblib.load('/content/drive/MyDrive/logreg_model.pkl')

def preprocess(text, vectorizer):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return vectorizer.transform([text])

def predict_xgb(text):
    vect = preprocess(text, vectorizer_xgb)
    pred = xgb_model.predict(vect)[0]
    return "🚫 Hate Speech" if pred == 1 else "✅ Not Hate Speech"

def predict_lgbm(text):
    vect = preprocess(text, vectorizer_lgbm)
    pred = lgbm_model.predict(vect)[0]
    return "🚫 Hate Speech" if pred == 1 else "✅ Not Hate Speech"

def predict_logreg(text):
    vect = preprocess(text, vectorizer_logreg)
    pred = logreg_model.predict(vect)[0]
    return "🚫 Hate Speech" if pred == 1 else "✅ Not Hate Speech"

user_input = input("Enter text to check for hate speech: ")
print("Choose a model:")
print("1 - XGBoost\n2 - LightGBM\n3 - Logistic Regression")

choice = input("Enter your choice (1/2/3): ")

if choice == '1':
    print("🔹 XGBoost says:", predict_xgb(user_input))
elif choice == '2':
    print("🔹 LightGBM says:", predict_lgbm(user_input))
elif choice == '3':
    print("🔹 Logistic Regression says:", predict_logreg(user_input))
else:
    print("❌ Invalid choice.")

